name: Build Chrome Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build extension
      run: npm run build
      
    - name: Create dist directory if it doesn't exist
      run: mkdir -p dist
      
    - name: Package extension files
      run: |
        cp -f public/manifest.json dist/ || true
        cp -f public/content.js dist/ || true
        cp -f public/content.css dist/ || true
        cp -f public/icon*.png dist/ || true
        ls -la dist/
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension
        path: dist/
        retention-days: 7